CREATE TYPE "public"."search_source_status" AS ENUM('pending', 'complete', 'failed');--> statement-breakpoint
CREATE TABLE "job_match_failures" (
	"id" text PRIMARY KEY NOT NULL,
	"resume_id" text NOT NULL,
	"job_id" text NOT NULL,
	"kind" text NOT NULL,
	"error_message" text NOT NULL,
	"attempts" integer NOT NULL,
	"failed_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "job_match_failures_resume_id_job_id_unique" UNIQUE("resume_id","job_id")
);
--> statement-breakpoint
ALTER TABLE "search_sources" ADD COLUMN "status" "search_source_status" DEFAULT 'pending' NOT NULL;--> statement-breakpoint
-- Hand-written backfill (ticket 4f88339, design c54b9e0 section 3.1), NOT
-- generated by drizzle-kit. The ADD COLUMN above stamps every pre-existing
-- row 'pending', which is wrong for history: every search_sources row that
-- exists at this instant belongs to an already-finished synchronous
-- (runDemoMatch / CLI / estimate) search whose `searches.status` is already
-- terminal. Their rows are never load-bearing -- the read path
-- short-circuits on the terminal `searches.status` before it ever reads
-- these columns -- but 'complete' is the honest value and it keeps the
-- invariant "a terminal search has no pending source rows" true for
-- history as well as for new searches. Safe as an unqualified UPDATE
-- because a migration runs exactly once: there is no row here yet that a
-- queue-driven search created.
UPDATE "search_sources" SET "status" = 'complete';--> statement-breakpoint
ALTER TABLE "search_sources" ADD COLUMN "linked_job_count" integer;--> statement-breakpoint
ALTER TABLE "search_sources" ADD COLUMN "error_kind" text;--> statement-breakpoint
ALTER TABLE "search_sources" ADD COLUMN "error_message" text;--> statement-breakpoint
ALTER TABLE "search_sources" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "searches" ADD COLUMN "completed_at" timestamp;--> statement-breakpoint
ALTER TABLE "job_match_failures" ADD CONSTRAINT "job_match_failures_resume_id_resumes_id_fk" FOREIGN KEY ("resume_id") REFERENCES "public"."resumes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "job_match_failures" ADD CONSTRAINT "job_match_failures_job_id_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_sources" ADD CONSTRAINT "search_sources_search_id_source_descriptor_id_unique" UNIQUE("search_id","source_descriptor_id");